const api=window.managerAPI,$=(id)=>document.getElementById(id);let settings={},quickLaunch=[];
const msg=(t,e=false)=>{const n=$('status');n.textContent=t;n.style.color=e?'var(--danger)':'var(--muted)'};
function fill(){['performanceMode','cpuLimit','ramLimit'].forEach(id=>$(id).value=settings[id]);$('memorySaver').checked=!!settings.memorySaver;$('focusMode').checked=!!settings.focusMode;$('cpuLimitValue').textContent=`${settings.cpuLimit||80}%`;$('ramLimitValue').textContent=`${settings.ramLimit||4096} MB`;$('appliedState').textContent=`${String(settings.performanceMode||'balanced').toUpperCase()} · ${settings.memorySaver?'SAVER ON':'SAVER OFF'}`;}
async function save(p){try{settings=await api.updateSettings(p);fill();msg('Performance policy saved and applied to open tabs.');await metrics()}catch(e){msg(e.message,true)}}
async function metrics(){try{const m=await api.getPerformanceMetrics();$('cpu').textContent=`${m.cpuPercent}%`;$('ram').textContent=`${m.browserMemoryMB} MB`;$('systemRam').textContent=`${m.systemMemoryPercent}%`;$('tabs').textContent=m.tabCount;$('cpuDetail').textContent=`${m.processCount} Electron processes`;$('systemRamDetail').textContent=`${m.freeMemoryGB} GB free of ${m.totalMemoryGB} GB`;$('tabsDetail').textContent=`${m.sleepingTabs||0} sleeping · ${m.audibleTabs} audible`;}catch(e){msg(e.message,true)}}
function renderItems(id,items,type){const root=$(id);root.replaceChildren(...items.map(item=>{const row=document.createElement('article');row.className='list-item';const body=document.createElement('div');const title=document.createElement('strong');title.textContent=item.name||item.text||'Untitled';const p=document.createElement('p');p.textContent=type==='workspace'?`${item.urls?.length||0} tabs · ${new Date(item.createdAt).toLocaleString()}`:new Date(item.createdAt).toLocaleString();body.append(title,p);const actions=document.createElement('div');if(type==='workspace'){const open=document.createElement('button');open.className='btn secondary';open.textContent='Open';open.onclick=()=>api.openWorkspace(item.id);actions.append(open)}const del=document.createElement('button');del.className='btn danger';del.textContent='Delete';del.onclick=async()=>{await(type==='workspace'?api.deleteWorkspace(item.id):api.deleteNote(item.id));await loadCollections()};actions.append(del);row.append(body,actions);return row;}));if(!items.length)root.innerHTML='<div class="muted">Nothing saved yet.</div>';}
async function loadCollections(){const d=await api.getGamingData();renderItems('workspaceList',d.workspaces||[],'workspace');renderItems('noteList',d.notes||[],'note')}
function renderLaunch(){const root=$('launchGrid');root.replaceChildren(...quickLaunch.map((item,index)=>{const wrap=document.createElement('div');wrap.className='launch-item';const open=document.createElement('button');open.className='launch-open';open.textContent=item.name;open.title=item.url;open.onclick=()=>api.openURL(item.url);const up=document.createElement('button');up.className='launch-move';up.textContent='↑';up.title='Move up';up.disabled=index===0;up.onclick=()=>moveLaunch(index,-1);const down=document.createElement('button');down.className='launch-move';down.textContent='↓';down.title='Move down';down.disabled=index===quickLaunch.length-1;down.onclick=()=>moveLaunch(index,1);const del=document.createElement('button');del.className='launch-delete';del.textContent='×';del.title='Remove';del.onclick=()=>removeLaunch(index);wrap.append(open,up,down,del);return wrap;}));}
async function persistLaunch(){quickLaunch=await api.saveQuickLaunch(quickLaunch);renderLaunch();msg('Quick Launch saved.');}
async function moveLaunch(index,delta){const next=index+delta;if(next<0||next>=quickLaunch.length)return;[quickLaunch[index],quickLaunch[next]]=[quickLaunch[next],quickLaunch[index]];await persistLaunch();}
async function removeLaunch(index){quickLaunch.splice(index,1);await persistLaunch();}
$('launchForm').onsubmit=async(e)=>{e.preventDefault();if(quickLaunch.length>=18)return msg('Quick Launch supports up to 18 shortcuts.',true);const name=$('launchName').value.trim(),url=$('launchUrl').value.trim();if(!name||!/^https?:\/\//i.test(url))return msg('Enter a name and a full http/https URL.',true);quickLaunch.push({id:crypto.randomUUID(),name,url});e.target.reset();await persistLaunch();};
$('restoreLaunch').onclick=async()=>{quickLaunch=await api.resetQuickLaunch();renderLaunch();msg('Default shortcuts restored.');};
$('close').onclick=()=>api.close();$('refresh').onclick=metrics;['performanceMode','memorySaver','focusMode'].forEach(id=>$(id).onchange=()=>save({[id]:$(id).type==='checkbox'?$(id).checked:$(id).value}));['cpuLimit','ramLimit'].forEach(id=>$(id).oninput=()=>{$(id+'Value').textContent=id==='cpuLimit'?`${$(id).value}%`:`${$(id).value} MB`},$(id).onchange=()=>save({[id]:Number($(id).value)}));$('mute').onclick=()=>api.toggleMute();$('screenshot').onclick=async()=>msg((await api.takeScreenshot())?.success?'Screenshot saved.':'Screenshot canceled.');$('reader').onclick=async()=>msg((await api.readerMode())?.success?'Reader mode opened.':'Reader mode unavailable.',false);$('saveWorkspace').onclick=async()=>{const name=prompt('Workspace name:','My workspace');if(name){await api.saveWorkspace(name);await loadCollections()}};$('addNote').onclick=async()=>{const text=$('noteInput').value.trim();if(!text)return;await api.addNote(text);$('noteInput').value='';await loadCollections()};
(async()=>{settings=await api.getSettings();quickLaunch=await api.getQuickLaunch();fill();renderLaunch();await Promise.all([metrics(),loadCollections()]);setInterval(metrics,5000)})();
