const api=window.managerAPI,$=(id)=>document.getElementById(id);let settings={};
function theme(value){document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value}
function show(section){document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===section));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.section===section))}
function message(text,error=false){$('status').textContent=text;$('status').style.color=error?'var(--danger)':'var(--muted)'}
async function save(patch){try{settings=await api.updateSettings(patch);fill();message('Settings saved.')}catch(e){message(e.message,true)}}
function fill(){theme(settings.theme);$('theme').value=settings.theme;$('defaultZoom').value=settings.defaultZoom;$('showBookmarksBar').checked=!!settings.showBookmarksBar;$('startupMode').value=settings.startup;$('searchEngine').value=settings.searchEngine;$('customSearchUrl').value=settings.customSearchUrl||'';$('downloadPathText').textContent=settings.downloadPath||'Use the system default folder.';$('askDownloadLocation').checked=!!settings.askDownloadLocation;$('doNotTrack').checked=!!settings.doNotTrack;$('blockTrackers').checked=!!settings.blockTrackers;$('blockPopups').checked=!!settings.blockPopups;$('restoreSession').checked=!!settings.restoreSession;$('autoLockMinutes').value=settings.autoLockMinutes||10;$('accentColor').value=settings.accentColor||'#7c5cff';$('performanceMode').value=settings.performanceMode||'balanced';$('memorySaver').checked=!!settings.memorySaver;$('animatedBackground').checked=!!settings.animatedBackground;$('sidebarEnabled').checked=!!settings.sidebarEnabled;$('gamingSounds').checked=!!settings.gamingSounds}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.section));
[['theme','theme'],['defaultZoom','defaultZoom'],['showBookmarksBar','showBookmarksBar'],['startupMode','startup'],['searchEngine','searchEngine'],['customSearchUrl','customSearchUrl'],['askDownloadLocation','askDownloadLocation'],['doNotTrack','doNotTrack'],['blockTrackers','blockTrackers'],['blockPopups','blockPopups'],['restoreSession','restoreSession'],['autoLockMinutes','autoLockMinutes'],['accentColor','accentColor'],['performanceMode','performanceMode'],['memorySaver','memorySaver'],['animatedBackground','animatedBackground'],['sidebarEnabled','sidebarEnabled'],['gamingSounds','gamingSounds']].forEach(([id,key])=>$(id).onchange=()=>save({[key]:$(id).type==='checkbox'?$(id).checked:$(id).type==='number'?Number($(id).value):$(id).value}));
$('chooseDownload').onclick=async()=>{const path=await api.chooseDownloadFolder();if(path)await save({downloadPath:path})};$('clearData').onclick=async()=>{if(confirm('Delete browsing history, cookies, cache and site storage?')){const r=await api.clearBrowsingData();message(r?.success?'Browsing data cleared.':'Could not clear browsing data.',!r?.success)}};$('close').onclick=()=>api.close();
(async()=>{const context=await api.getContext();$('version').textContent=context.version;settings=await api.getSettings();fill()})();
